/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class User */

#ifndef _Included_User
#define _Included_User
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     User
 * Method:    load
 * Signature: ()LNode;
 */
JNIEXPORT jobject JNICALL Java_User_load
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
