/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class User */

#ifndef _Included_User
#define _Included_User
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     User
 * Method:    func
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_User_func
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
